// route

// game
export const POKEMON = "POKEMON";

export const LEVEL = "LEVEL";
export const NATURE_SET = "NATURE_SET";
export const NATURE_RESET = "NATURE_RESET";
export const NATURE_MODIFIER_ATTACK = "NATURE_MODIFIER_ATTACK";
export const NATURE_MODIFIER_DEFENSE = "NATURE_MODIFIER_DEFENSE";
export const NATURE_MODIFIER_SPECIAL_ATTACK = "NATURE_MODIFIER_SPECIAL_ATTACK";
// prettier-ignore
export const NATURE_MODIFIER_SPECIAL_DEFENSE ="NATURE_MODIFIER_SPECIAL_DEFENSE";
export const NATURE_MODIFIER_SPEED = "NATURE_MODIFIER_SPEED";
export const NATURE_MODIFIER_SET = "NATURE_MODIFIER_SET";
export const NATURE_MODIFIER_RESET = "NATURE_MODIFIER_RESET";
export const BASE_STAT_HP = "BASE_STAT_HP";
export const BASE_STAT_ATTACK = "BASE_STAT_ATTACK";
export const BASE_STAT_DEFENSE = "BASE_STAT_DEFENSE";
export const BASE_STAT_SPECIAL_ATTACK = "BASE_STAT_SPECIAL_ATTACK";
export const BASE_STAT_SPECIAL_DEFENSE = "BASE_STAT_SPECIAL_DEFENSE";
export const BASE_STAT_SPEED = "BASE_STAT_SPEED";
export const BASE_STAT_SET = "BASE_STAT_SET"; // used for setting all base stats at once
export const BASE_STAT_RESET = "BASE_STAT_RESET";
export const CURRENT_STAT_HP = "CURRENT_STAT_HP";
export const CURRENT_STAT_ATTACK = "CURRENT_STAT_ATTACK";
export const CURRENT_STAT_DEFENSE = "CURRENT_STAT_DEFENSE";
export const CURRENT_STAT_SPECIAL_ATTACK = "CURRENT_STAT_SPECIAL_ATTACK";
export const CURRENT_STAT_SPECIAL_DEFENSE = "CURRENT_STAT_SPECIAL_DEFENSE";
export const CURRENT_STAT_SPEED = "CURRENT_STAT_SPEED";
export const CURRENT_STAT_SET = "CURRENT_STAT_SET";
export const CURRENT_STAT_RESET = "CURRENT_STAT_RESET";
export const IV_HP = "IV_HP";
export const IV_ATTACK = "IV_ATTACK";
export const IV_DEFENSE = "IV_DEFENSE";
export const IV_SPECIAL_ATTACK = "IV_SPECIAL_ATTACK";
export const IV_SPECIAL_DEFENSE = "IV_SPECIAL_DEFENSE";
export const IV_SPEED = "IV_SPEED";
export const IV_SET = "IV_SET";
export const IV_RESET = "IV_RESET";
export const EV_HP = "EV_HP";
export const EV_ATTACK = "EV_ATTACK";
export const EV_DEFENSE = "EV_DEFENSE";
export const EV_SPECIAL_ATTACK = "EV_SPECIAL_ATTACK";
export const EV_SPECIAL_DEFENSE = "EV_SPECIAL_DEFENSE";
export const EV_SPEED = "EV_SPEED";
export const EV_SET = "EV_SET";
export const EV_RESET = "EV_RESET";
